name: macOS app build (PyInstaller) with ffmpeg 8

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - '**.py'
      - 'pyinstaller.spec'
      - 'requirements.txt'
      - 'assets/**'
      - '.github/workflows/macos-build.yml'

jobs:
  build:
    runs-on: macos-13  # x86_64 runner; we'll also fetch arm64 ffmpeg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt pyinstaller==6.10.0

      - name: Prepare ffmpeg v8 (arm64 and x86_64)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p assets/ffmpeg/mac/arm64 assets/ffmpeg/mac/x86_64
          # Download static builds for macOS; using evermeet.cx mirrors for v8
          # x86_64
          curl -L -o ffmpeg-x86_64.zip "https://evermeet.cx/ffmpeg/ffmpeg-8.0.zip"
          unzip -o ffmpeg-x86_64.zip -d assets/ffmpeg/mac/x86_64
          mv assets/ffmpeg/mac/x86_64/ffmpeg assets/ffmpeg/mac/x86_64/ffmpeg
          chmod +x assets/ffmpeg/mac/x86_64/ffmpeg
          # arm64
          curl -L -o ffmpeg-arm64.zip "https://evermeet.cx/ffmpeg/ffmpeg-8.0-arm64.zip"
          unzip -o ffmpeg-arm64.zip -d assets/ffmpeg/mac/arm64
          mv assets/ffmpeg/mac/arm64/ffmpeg assets/ffmpeg/mac/arm64/ffmpeg
          chmod +x assets/ffmpeg/mac/arm64/ffmpeg

      - name: Build app
        run: |
          rm -rf build dist || true
          pyinstaller -y --clean pyinstaller.spec

      - name: Zip artifacts
        run: |
          cd dist
          zip -r "DatasetCutter-macOS-app.zip" "Dataset Cutter.app"
          zip -r "DatasetCutter-macOS-cli.zip" "DatasetCutter"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DatasetCutter-macOS-with-ffmpeg8
          path: |
            dist/DatasetCutter/**
            dist/Dataset Cutter.app/**
          if-no-files-found: error

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/DatasetCutter-macOS-app.zip
            dist/DatasetCutter-macOS-cli.zip
